-- First, remove the table if it exists
drop table if exists bookmarks;

-- Create the table anew
CREATE TABLE bookmarks (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  website TEXT,
  descript TEXT,
  rating INT
);

-- insert some test data
-- Using a multi-row insert statement here
insert into bookmarks (title, website, descript)
values
  ('Youtube', 'Youtube.com', 'video site'),
  ('Digital Ocean - PSQL tut', 'https://www.digitalocean.com/community/tutorials/how-to-install-and-use-postgresql-on-ubuntu-18-04', 'A tutorial on installing/using Postgres on Ubuntu'),
  ('BPMN.io', 'https://demo.bpmn.io/new', 'modeller'),
  ('Juniors in Tech', 'https://jobs.juniorsintech.com/', 'A job board'),
  ('React - conditional rendering', 'https://reactjs.org/docs/conditional-rendering.html', 'React documentation on conditional rendering'),
  ('TinyPNG', 'https://tinypng.com/', 'Make images smaller'),
  ('Coolors', 'https://coolors.co/fcefef-7fd8be-a1fcdf-fcd29f-fcab64', 'Website color generator'),
  ('Web2py', 'http://web2py.com/books/default/chapter/29/02', 'A book about Web2py and python'),
  ('Blog - Gatsby', 'https://www.gatsbyjs.org/blog/2017-11-09-why-i-created-my-blog-with-gatsby-and-contentful/', 'A blog post about creating a blog using Gatsby and other tools'),
  ('Graph Cool', 'https://www.graph.cool/', 'A backend framework for GraphQL');